version: '3'

services:
  python_service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: totalsegmentator
    ports:
      - "8000:8000"
    command: python -m uvicorn totalsegmentation:app --host 0.0.0.0 --port 8000 
